CREATE TABLE `esat_db`.`locations` (
	`COMP_ID` char(4) NOT NULL,
	`BR_CD` char(3) NOT NULL,
	`USR_ID` char(12) NOT NULL,
	`ACT_ID` char(12) NOT NULL,
	`FRST_NM` varchar(75) NULL,
	`LST_NM` varchar(75) NULL,
	`FLL_NM` varchar(100) NULL,
	`NCK_NM` varchar(100) NULL,
	`MOB_NO` varchar(15) NULL,
	`EML_ADD` varchar(50) NULL,
	`HM_ADDR` varchar(350) NULL,
	`PRSNT_ADDR` varchar(200) NULL,
	`LOC_REG` varchar(50) NULL,
	`LOC_PROV` varchar(50) NULL,
	`LOC_MUN` varchar(50) NULL,
	`GNDR` char(1) NULL,
	`MRTL_STAT` char(1) NULL,
	`CTZNSHP` varchar(125) NULL,
	`IMG_URL` varchar(500) NULL,
	`BRT_DT` varchar(25) NULL,
	`RGS_TRN_DT` char(8) NULL,
	`RGS_TRN_TM` char(6) NULL,
	`RGS_TRN_TS` datetime NULL,
	`RGS_USR_ID` varchar(50) NULL,
	`UPD_TRN_DT` char(8) NULL,
	`UPD_TRN_TM` char(6) NULL,
	`UPD_TRN_TS` datetime NULL,
	`UPD_USR_ID` varchar(50) NULL,
	`LOC_BRGY` varchar(15) NULL,
	`BLD_TYP` varchar(3) NULL,
	`NATNLTY` varchar(3) NULL,
	`PRF_PIC` varchar(500) NULL,
	`OCCPTN` varchar(75) NULL,
	`SKLLS` varchar(50) NULL,
	`MDL_NM` varchar(75) NULL,
	`XPR_DT` varchar(50) NULL,
	`VALFRM_DT` varchar(12) NULL,
	`VALTO_DT` varchar(12) NULL,
	`NXTKN_NM` varchar(125) NULL,
	`NXTKN_NO` varchar(25) NULL,
	`SGNTR_PIC` varchar(500) NULL,
	`FRST_NM2` varchar(50) NULL,
	`LST_NM2` varchar(50) NULL,
	`BRT_DT2` varchar(25) NULL,
	`GRP_ID` bigint NULL,
	`GEO_LCTN` varchar(250) NULL,
  PRIMARY KEY (`COMP_ID`))
ENGINE = InnoDB;